package GearTrain.Controller;

import GearTrain.Exceptions.GearTrainNonMeshableElements;
import GearTrain.Model.GearTrain;
import GearTrain.Model.Parser.XMLParser;
import GearTrain.View.View;

public class GearTrainController {
	private View view;
	private GearTrain gear_train_model;
	/**
	 * Create a new GearTrainController with View view and a GearTrain generated by
	 * 		an input xml file
	 * @param view
	 * @param input_file
	 */
	public GearTrainController(View view, String input_file){
		this.setView(view);
		this.setGearTrainModel(XMLParser.loadGearTrain(input_file));
	}

	public void testController(){
		try {
			System.out.println(gear_train_model.getOutputSpeed());
		} catch (GearTrainNonMeshableElements e) {
			e.printStackTrace();
		}
	}
	
	public void setView(View view) {
		this.view = view;
	}
	
	public void setGearTrainModel(GearTrain gear_train_model) {
		this.gear_train_model = gear_train_model;
	}
}
